
services:
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: "uvicorn main:app --host 0.0.0.0 --reload"
    working_dir: /app
  
  client:
    build:
      context: ./client
    depends_on:
      - server
    volumes:
      - ./client:/app
    command: python main.py
    working_dir: /app
    